server:
  port: 5673  # Mude para outra porta (8081, 8082, etc.)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notificacao
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  
  # ADICIONAR CONFIGURAÇÃO DO RABBITMQ
  rabbitmq:
    host: localhost
    port: 5672  # Esta é a porta do RabbitMQ, NÃO do servidor web!
    username: guest
    password: guest
    listener:
      simple:
        auto-startup: true
        missing-queues-fatal: false